server:
  port: 8082

spring:
  datasource:
    url: jdbc:mariadb://www.oways.co.kr:3306/FEIGN2_DB
    username: root
    password: asdfasdf
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: schedule-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.example.common.dto