server:
  port: 8082

spring:
  datasource:
    url: jdbc:mariadb://www.oways.co.kr:3306/FEIGN_DB
    username: root
    password: asdfasdf
  mybatis:
    mapper-locations: classpath:/mapper/**/*.xml
    type-aliases-package: com.example.common.dto