server:
  port: 8082                      # 유레카 정보 필수

spring:
  application:
    name: server2                 # 유레카 정보 필수
  datasource:
    url: jdbc:mariadb://www.oways.co.kr:3306/FEIGN2_DB
    username: root
    password: asdfasdf

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      #  신뢰성 향상, 재시도 설정, 중복 처리 지원, DLT(Dead Letter Topic)
      group-id: scheduler-worker
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest              # 처음부터 읽기 (옵션: latest, earliest)
      enable-auto-commit: false                # false : 수동 커밋 사용 (Listener에서 ack)
      properties:
        isolation.level: read_committed        # 정확히 한번 처리에 필요 (옵션: read_uncommitted)

    producer:
      group-id: schedule-group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all                                # 모든 리플리카가 ack 줄 때까지 기다림
      retries: 3                               # 전송 실패 시 재시도
      enable-idempotence: true                 # 중복 전송 방지 (idempotent producer)
      delivery-timeout-ms: 30000               # 전체 전송 타임아웃
      linger-ms: 5                             # 배치 전 대기 시간 (성능 최적화용)

    listener:
      ack-mode: manual                         # Listener에서 수동 커밋 필요
      missing-topics-fatal: false              # 없는 토픽 있을 경우 에러 무시

    retry:
      topic:
        enabled: true                          # @RetryableTopic 지원 활성화
        attempts: 3                            # 최대 재시도 횟수
        backoff:
          delay: 2000                          # 재시도 간격(ms)
        dlt:
          topic-suffix: .DLT                   # 실패 시 DLT 토픽으로 전송

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.example.common.dto


eureka:
  client:
    service-url:                 # Eureka Server의 주소 (※ 여러 개일 경우 쉼표로 나열 가능)
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true   # Eureka 서버에 등록(register) 하겠다는 의미
                                 # false로 하면, 클라이언트로만 동작하고 Eureka에 자신을 등록하지 않음
    fetch-registry: true         # Eureka 서버로부터 다른 서비스의 정보를 가져오겠다(fetch) 는 의미
                                 # → 이 설정이 true이면, 이 애플리케이션은 다른 서비스의 위치를 조회
    healthcheck:                 # Spring Boot의 Actuator Health Check를 Eureka에 통합시켜 사용하겠다는 의미
      enabled: true
  instance:
    prefer-ip-address: true      # # 호스트네임 대신 IP로 등록
    instance-id: ${spring.application.name}:${server.port}  # 인스턴스 구분용
