server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://www.oways.co.kr:3306/FEIGN_DB
    username: root
    password: asdfasdf
  application:
    name: server1
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.example.common.dto
